_prefs: 
  mapid: tgirgin.366a25c3
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -46.582
  - 40.9799
  - 3
description: A map based on the famous Tintin comic book
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: Tintin
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v5,tgirgin.c632ozf3"
styles: 
  - style.mss
  - country_label.mss
  - place_label.mss
  - land_cover.mss
  - hillshade.mss
  - road_label.mss
  - water_label.mss
template: ''
